#!/usr/bin/env bash
# ----------------+
# Shell Shortcuts |
# ----------------+

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias _="sudo"
alias x="exit"
alias reload="source ~/.bashrc"
alias reload_profile="source ~/.bash_profile"
alias path="echo -e ${PATH//:/\\n}"  # prints each PATH entry on a separate line
alias vscode="cmd //C code $*"
